Repository Now-You-Run/You-Run-Server, pull requests merged in 2025-07, with the labels that each got.

#7 [feature] 트랙 저장 및 불러오기 기능 추가
  build.gradle
  src/main/java/com/running/you_run/auth/config/SecurityConfig.java
  src/main/java/com/running/you_run/global/exception/ErrorCode.java
  src/main/java/com/running/you_run/gps/controller/GpsController.java
  src/main/java/com/running/you_run/gps/entity/RunningTrack.java
  src/main/java/com/running/you_run/gps/payload/dto/CoordinateDto.java
  src/main/java/com/running/you_run/gps/payload/dto/CoordinateResponseDto.java
  src/main/java/com/running/you_run/gps/payload/request/TrackStoreRequest.java
  src/main/java/com/running/you_run/gps/payload/response/TrackPathResponse.java
  src/main/java/com/running/you_run/gps/repository/TrackRepository.java
  src/main/java/com/running/you_run/gps/service/TrackService.java
  src/main/resources/application-prod.properties
Labels: Feature

#12 [feature] 트랙에 주소, 시작점 추가
  src/main/java/com/running/you_run/auth/Enum/FriendStatus.java
  src/main/java/com/running/you_run/auth/config/SecurityConfig.java
  src/main/java/com/running/you_run/auth/controller/FriendController.java
  src/main/java/com/running/you_run/auth/entity/Friend.java
  src/main/java/com/running/you_run/auth/repository/FriendRepository.java
  src/main/java/com/running/you_run/auth/service/FriendService.java
  src/main/java/com/running/you_run/global/exception/ErrorCode.java
  src/main/java/com/running/you_run/running/entity/RunningTrack.java
  src/main/java/com/running/you_run/running/payload/dto/TrackListItemDto.java
  src/main/java/com/running/you_run/running/service/KakaoGeoService.java
  src/main/java/com/running/you_run/running/service/TrackService.java
  src/main/resources/application-prod.properties
Labels: Feature

#11 [feature] 마이페이지와 유저정보관리 기능 추가
  gradlew
  src/main/java/com/running/you_run/auth/config/SecurityConfig.java
  src/main/java/com/running/you_run/auth/controller/MypageController.java
  src/main/java/com/running/you_run/auth/controller/RaceResultController.java
  src/main/java/com/running/you_run/auth/dto/MyPageDto.java
  src/main/java/com/running/you_run/auth/dto/RaceResultDto.java
  src/main/java/com/running/you_run/auth/dto/RaceResultSaveDto.java
  src/main/java/com/running/you_run/auth/entity/RaceResult.java
  src/main/java/com/running/you_run/auth/entity/User.java
  src/main/java/com/running/you_run/auth/repository/MyPageQueryRepository.java
  src/main/java/com/running/you_run/auth/repository/MyPageQueryRepositoryImpl.java
  src/main/java/com/running/you_run/auth/repository/RaceResultRepository.java
  src/main/java/com/running/you_run/auth/service/MypageService.java
  src/main/java/com/running/you_run/auth/service/RaceResultService.java
  src/main/java/com/running/you_run/auth/util/JwtFilter.java
  src/main/resources/application.properties
Labels: Feature

#21 fix: 마이페이지 트랙 기록 못불러오는 에러 수정
  src/main/java/com/running/you_run/running/payload/dto/RecordDto.java
Labels: Fix

#27 [feature] 경로 단순화 로직 추가
  src/main/java/com/running/you_run/running/payload/dto/TrackListItemDto.java
  src/test/java/com/running/you_run/running/fixture/RecordFixture.java
Labels: Feature

#28 feature: record테이블에 user_path칼럼에 대한 타입 바꾸기
  src/main/java/com/running/you_run/running/payload/dto/CoordinateDto.java
  src/main/java/com/running/you_run/running/payload/request/RecordStoreRequest.java
  src/main/java/com/running/you_run/running/util/CoordinateConverter.java
Labels: Feature

#29 feature: 기록테이블에 봇페이스 기록 저장
  src/main/java/com/running/you_run/running/entity/Record.java
  src/main/java/com/running/you_run/running/payload/request/RecordStoreRequest.java
Labels: Feature

#32 [fix]트랙 저장 시에 유저 아이디가 반영이 안되는 문제 해결
  src/main/java/com/running/you_run/running/payload/request/RunningTrackStoreRequest.java
  src/main/java/com/running/you_run/running/service/TrackService.java
Labels: Fix

#36 feature:기록불러오기 api 수정
  src/main/java/com/running/you_run/running/service/RecordService.java
Labels: Feature

#37 [feature] s3 지도 썸네일 업로드, 에러 검출 개선,서버트랙만 보이도록 수정
  build.gradle
  src/main/java/com/running/you_run/global/config/AsyncConfig.java
  src/main/java/com/running/you_run/global/config/S3Config.java
  src/main/java/com/running/you_run/global/config/SecurityConfig.java
  src/main/java/com/running/you_run/global/exception/ErrorCode.java
  src/main/java/com/running/you_run/global/exception/GlobalExceptionHandler.java
  src/main/java/com/running/you_run/running/controller/TrackController.java
  src/main/java/com/running/you_run/running/entity/RunningTrack.java
  src/main/java/com/running/you_run/running/payload/dto/TrackListItemDto.java
  src/main/java/com/running/you_run/running/repository/TrackRepository.java
  src/main/java/com/running/you_run/running/service/S3UploadService.java
  src/main/java/com/running/you_run/running/service/StaticMapService.java
  src/main/java/com/running/you_run/running/service/TrackService.java
  src/main/java/com/running/you_run/running/util/PolylineEncoder.java
  src/main/java/com/running/you_run/user/util/JwtFilter.java
  src/main/resources/application-prod.properties
Labels: Feature

#39 feature: 트랙 상세페이지에서 랭킹에 대한 recordId 반환,
  src/main/java/com/running/you_run/global/exception/ErrorCode.java
  src/main/java/com/running/you_run/running/controller/RecordController.java
  src/main/java/com/running/you_run/running/payload/dto/TrackRecordDto.java
  src/main/java/com/running/you_run/running/service/RecordService.java
  src/main/java/com/running/you_run/running/service/TrackService.java
Labels: Feature

#59 [fix] 트랙 목록 페이지네이션 stable 정렬 추가
  src/main/java/com/running/you_run/running/controller/TrackController.java
  src/main/java/com/running/you_run/running/repository/TrackRepository.java
  src/main/java/com/running/you_run/running/service/StaticMapService.java
  src/main/java/com/running/you_run/running/service/TrackService.java
Labels: Fix, Feature

#60 [fix] findTracksOrderByClose sql 문법 수정
  src/main/java/com/running/you_run/running/repository/TrackRepository.java
Labels: Fix

#64 [docs] README.md 수정
  README.md
Labels: Docs

#67 fix: 아바타 통일 버그 수정
  src/main/java/com/running/you_run/user/controller/AvatarController.java
Labels: Fix
